# primes = 'OOO'
# for i in range(3, 10000):
#     isPrime = True
#     for j in range(2, i//2 + 1):
#         if i % j == 0:
#             isPrime = False
#             primes += 'O'
#             break
#     if isPrime:
#         primes += 'I'
#
# print(primes)

primes = 'OOOIOIOIOOOIOIOOOIOIOOOIOOOOOIOIOOOOOIOOOIOIOOOIOOOOOIOOOOOIOIOOOOOIOOOIOIOOOOOIOOOIOOOOOIOOOOOOOIOOOIOI' \
         'OOOIOIOOOIOOOOOOOOOOOOOIOOOIOOOOOIOIOOOOOOOOOIOIOOOOOIOOOOOIOOOIOOOOOIOOOOOIOIOOOOOOOOOIOIOOOIOIOOOOOOOO' \
         'OOOIOOOOOOOOOOOIOOOIOIOOOIOOOOOIOIOOOOOOOOOIOOOOOIOOOOOIOOOOOIOIOOOOOIOOOIOIOOOOOOOOOIOOOOOOOOOOOOOIOOOI' \
         'OIOOOIOOOOOOOOOOOOOIOOOOOIOOOOOOOOOIOIOOOIOOOOOIOOOOOOOIOOOOOIOOOOOIOOOIOOOOOIOOOOOOOIOOOIOOOOOOOIOOOOOO' \
         'OOOIOIOOOOOOOOOIOIOOOOOIOOOIOOOOOIOOOOOOOIOOOIOIOOOIOOOOOOOOOOOIOOOOOOOIOOOIOOOOOOOIOOOIOOOOOIOOOOOOOOOO' \
         'OIOIOOOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOIOOOOOIOOOOOIOIOOOOOIOOOOOOOOOIOOOOOIOOOOOIOIOOOOOIOOOOOIOOOIOIOOOO' \
         'OOOOOOOIOOOOOOOOOIOIOOOIOOOOOIOOOOOIOIOOOOOOOOOOOIOOOIOOOOOIOOOOOOOIOOOOOOOOOIOOOOOOOIOOOOOOOOOIOOOOOOOI' \
         'OOOOOIOOOOOIOOOIOOOOOOOIOOOOOIOOOIOOOOOOOIOOOIOOOOOOOOOOOOOIOOOOOOOOOIOOOOOOOOOOOIOIOOOOOOOOOIOIOOOIOIOO' \
         'OOOOOOOIOOOOOOOOOOOOOIOOOIOIOOOIOOOOOOOOOOOOOIOOOIOIOOOIOOOOOOOOOOOOOOOOOOOIOOOIOOOOOOOIOOOOOOOOOIOOOOOO' \
         'OIOOOIOOOOOIOOOOOIOOOOOOOOOOOOOIOOOIOOOOOIOOOOOIOOOOOOOIOOOOOIOOOOOOOOOOOIOOOIOOOOOIOIOOOOOOOOOIOIOOOOOI' \
         'OOOOOOOOOIOIOOOOOOOOOIOIOOOOOIOOOOOOOOOOOOOOOOOIOOOIOIOOOIOOOOOIOOOOOIOOOOOOOIOOOOOIOOOOOIOOOOOOOOOOOOOO' \
         'OOOOOOOIOIOOOOOOOOOIOOOOOOOIOOOOOOOOOIOOOOOIOOOOOIOOOOOOOIOOOOOOOOOOOIOOOIOOOOOIOOOOOIOIOOOOOIOOOOOOOOOO' \
         'OIOOOOOOOOOIOOOOOOOOOOOOOOOOOIOIOOOIOOOOOIOIOOOOOIOOOIOIOOOIOOOOOOOOOOOIOIOOOOOIOOOOOOOOOOOOOOOOOOOOOOOO' \
         'OOOOOOOOOIOOOOOIOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOIOOOOOOOOOIOOOOOOOOOOOOOIOOOIOIOOOIOOOOOIOOOOOOOIOOOIOIOO' \
         'OOOIOOOOOOOOOOOIOOOOOOOOOIOIOOOIOIOOOIOOOOOIOOOOOOOOOOOIOOOOOOOOOOOIOOOOOOOIOOOOOOOOOOOIOOOOOIOOOIOOOOOI' \
         'OOOOOOOIOOOIOOOOOOOIOOOIOOOOOOOOOOOOOIOOOIOOOOOIOIOOOIOOOOOIOIOOOOOIOOOOOOOOOIOOOOOOOOOOOOOOOOOOOIOOOOOI' \
         'OOOIOIOOOOOOOOOOOOOOOOOOOOOOOIOOOIOIOOOOOOOOOIOOOOOOOOOOOIOIOOOOOOOOOIOOOOOOOIOOOOOIOOOOOIOOOOOIOOOOOOOO' \
         'OOOOOOOOOIOOOOOIOOOIOIOOOOOOOOOOOIOOOOOOOOOIOOOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOIOOOOOOOOOOOOOIOOOOOIOOOI' \
         'OIOOOIOIOOOOOOOOOIOOOOOOOOOOOIOOOOOIOOOOOIOOOOOOOOOOOOOOOOOIOIOOOOOOOOOOOOOOOIOIOOOOOOOOOOOOOOOOOOOOOIOO' \
         'OOOIOOOOOOOIOOOOOIOOOIOIOOOIOOOOOOOIOOOOOIOOOOOOOOOIOIOOOOOOOOOIOOOOOOOOOOOOOIOOOOOOOOOIOOOOOIOOOOOOOOOO' \
         'OIOIOOOIOIOOOOOOOOOIOOOOOOOOOOOIOIOOOOOOOOOOOOOOOIOIOOOOOIOOOIOIOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOIOOOO' \
         'OOOOOOOOOOOOOOOOOOOIOOOIOOOOOIOOOOOOOIOOOOOOOOOOOOOOOIOIOOOIOOOOOOOIOOOOOOOOOOOOOOOIOIOOOIOOOOOOOIOOOOOI' \
         'OOOOOIOOOIOOOOOOOOOOOIOIOOOOOOOOOOOOOOOOOOOOOIOOOOOIOIOOOOOIOOOIOOOOOIOOOOOOOOOOOOOIOOOOOIOOOIOIOOOOOIOO' \
         'OIOOOOOIOOOOOOOOOOOIOOOOOIOOOOOIOOOOOOOOOOOOOIOOOIOOOOOIOOOOOOOOOOOIOOOOOOOIOOOOOIOOOIOOOOOOOOOOOOOOOOOO' \
         'OOOOOOOIOOOOOOOOOOOOOOOOOIOOOOOOOOOIOOOOOOOIOOOIOOOOOIOIOOOOOIOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOOOIOIOOOOOO' \
         'OOOOOOOOOIOOOOOOOIOOOIOOOOOOOOOOOIOOOOOOOOOOOOOIOOOOOOOOOIOIOOOIOOOOOOOIOOOOOIOOOOOIOOOIOIOOOIOOOOOIOOOO' \
         'OOOIOOOIOIOOOOOIOOOOOOOOOIOIOOOOOOOOOIOOOOOOOIOOOIOOOOOOOOOOOOOIOOOOOOOOOIOOOOOOOOOOOIOIOOOOOIOOOIOIOOOO' \
         'OOOOOOOOOOOIOOOOOOOOOOOOOIOOOIOOOOOIOOOOOOOIOOOOOIOOOIOOOOOOOOOOOOOOOOOIOOOOOOOIOOOOOOOOOIOOOOOIOOOOOIOO' \
         'OOOOOIOOOOOOOOOIOOOOOOOOOOOIOOOOOOOOOOOOOIOOOIOOOOOIOOOOOIOIOOOOOOOOOOOOOOOOOOOOOOOOOOOIOIOOOOOOOOOIOOOO' \
         'OOOIOOOIOOOOOOOOOOOOOIOOOIOOOOOOOIOOOOOOOOOOOIOOOOOIOOOOOOOOOOOIOOOIOOOOOIOOOOOOOOOOOOOOOOOOOIOOOOOOOOOI' \
         'OIOOOOOOOOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOIOOOIOIOOOOOOOOOOOIOOOOOIOOOIOOOOOOOOOOOIOOOOOIOOOOOOOIOOOIOO' \
         'OOOOOIOOOOOOOOOOOOOOOOOOOOOIOIOOOIOIOOOOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOIOIOOOOOIOOOOOIOOOOOIOOOIOOOO' \
         'OIOIOOOOOOOOOOOIOOOIOOOOOOOOOOOIOIOOOOOOOOOIOIOOOOOOOOOOOOOOOIOIOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOOOOOO' \
         'OIOOOOOOOOOOOOOOOIOOOOOOOIOOOIOIOOOIOIOOOOOOOOOOOOOOOOOOOOOIOOOOOOOIOOOOOOOOOOOIOOOOOIOOOOOOOOOIOIOOOIOO' \
         'OOOIOIOOOOOIOOOOOOOOOIOIOOOOOOOOOOOIOOOOOOOOOIOIOOOOOOOOOIOOOOOOOOOOOOOIOOOOOIOOOIOOOOOIOOOOOOOIOOOOOIOO' \
         'OOOIOOOOOOOOOOOOOOOIOOOOOOOOOOOIOIOOOIOOOOOOOOOOOOOIOOOOOIOOOIOOOOOOOIOOOOOOOOOIOOOOOOOIOOOOOIOOOOOIOOOO' \
         'OOOOOOOOOOOOOOOOOIOOOOOIOIOOOOOOOOOIOOOOOOOOOOOOOIOOOIOOOOOIOOOOOOOOOOOOOOOOOIOIOOOOOOOOOIOOOOOOOOOOOOOI' \
         'OOOIOIOOOOOOOOOIOOOOOOOOOOOOOIOOOIOOOOOOOIOOOOOOOOOOOOOOOOOIOOOIOOOOOIOIOOOIOOOOOIOIOOOOOOOOOOOIOOOIOOOO' \
         'OOOOOOOOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOOOIOIOOOIOOOOOIOOOOOIOIOOOOOIOOOOOOOOOOOOOOOOOOOOOIOIOOOO' \
         'OIOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOIOIOOOOOIOOOOOOOOOOOIOOOOOOOOOOOOOOOIOIOOOIOOOOOIOOOOOOOOOOOOOIOOOIOI' \
         'OOOOOOOOOOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOIOOOOOIOIOOOOOOOOOIOIOOOOOOOOOIOIOOOOOOOOOIOOOOOIOIOO' \
         'OOOOOOOIOIOOOOOOOOOIOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOIOIOOOOOOOOOIOOOOOOOIOOOOOIOOOO' \
         'OOOOOIOOOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOIOOOOOOOOOOOIOIOOOOOOOOOOOOOOOOOIOOOOOIOOOIOOOOOIOOOOOIOOOOOOOO' \
         'OOOOOOOOOIOIOOOOOOOOOIOOOOOOOOOOOOOIOOOOOIOOOIOIOOOIOOOOOOOOOOOOOOOOOOOOOOOIOIOOOOOOOOOOOIOOOOOIOOOOOOOO' \
         'OOOOOOOIOOOOOOOIOOOOOIOOOOOIOOOOOOOOOOOOOOOOOIOOOOOOOOOOOOOOOIOIOOOIOOOOOIOIOOOOOIOOOOOIOOOOOOOOOIOOOOOI' \
         'OOOOOOOOOOOIOOOOOOOOOOOIOOOOOOOOOOOOOOOOOIOIOOOOOIOOOIOOOOOOOOOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOI' \
         'OOOIOIOOOIOOOOOIOIOOOOOOOOOOOIOOOIOOOOOOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOIOOOOOIOOOOOOOOOO' \
         'OIOOOOOOOOOOOOOIOOOOOIOOOOOOOOOIOOOOOOOOOOOIOIOOOIOOOOOIOOOOOOOIOOOOOIOOOOOOOOOIOIOOOIOOOOOOOOOOOOOIOOOO' \
         'OIOOOOOIOOOIOOOOOIOIOOOOOOOOOIOIOOOOOOOOOOOOOOOIOOOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOIOOOIOOOOOIOOOOOOOO' \
         'OOOIOIOOOOOIOOOOOIOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOIOOOIOOOOOOOIOOOOOOOOOIOOOOOOOIOO' \
         'OOOOOOOOOIOOOOOOOOOOOOOOOOOIOOOIOIOOOIOOOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOOOIOOOOOIOIOOOOOOOOOOOOOOOIOOOOOI' \
         'OOOOOIOOOOOOOOOOOOOIOOOOOOOOOIOOOOOOOOOOOOOIOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOOOIOOOOOIOOOOOIOOOOOOOI' \
         'OOOOOIOOOIOIOOOOOOOOOOOIOOOOOIOOOIOIOOOOOIOOOOOOOOOOOOOOOOOOOOOIOOOOOIOIOOOIOOOOOOOOOOOOOOOOOIOIOOOIOOOO' \
         'OOOOOOOIOIOOOOOIOOOIOOOOOOOOOOOOOOOOOOOOOOOOOIOOOOOIOOOOOIOOOIOOOOOOOIOOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOO' \
         'OOOOOOOIOOOOOOOOOOOOOOOIOIOOOOOIOOOIOIOOOIOIOOOOOOOOOIOOOOOOOOOOOOOIOOOOOIOOOIOOOOOOOIOOOOOOOOOIOOOOOIOO' \
         'OOOOOOOOOOOOOOOOOIOOOIOIOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOIOOOOOOOIOOOOOOOOOIOOOOOIOOOOOIOOOOOOOIOO' \
         'OOOIOOOOOOOOOOOIOOOIOOOOOIOIOOOOOIOOOIOOOOOIOIOOOOOOOOOIOIOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOOOOOOOIOOOI' \
         'OOOOOOOOOOOIOOOOOOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOOOOOOOIOOOIOOOOOOOOOOOOOOOOOIOO' \
         'OOOOOIOOOOOIOOOIOOOOOIOOOOOOOOOOOOOIOOOOOIOOOOOIOOOOOOOOOIOIOOOOOOOOOIOOOOOOOOOOOIOOOOOOOIOOOOOOOOOIOIOO' \
         'OOOOOOOIOOOOOOOIOOOOOOOOOOOIOOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOIOIOOOIOOOOOOOIOOOOOIOOOIOOOOOOOIOOOOOOOOOO' \
         'OOOOOOOIOOOOOOOOOIOOOOOIOOOOOIOIOOOOOIOOOOOOOOOIOOOOOOOOOOOIOIOOOOOOOOOIOOOOOIOOOOOIOOOOOIOOOOOOOIOOOOOI' \
         'OOOOOOOOOIOOOOOIOIOOOOOIOOOOOIOOOOOIOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOOOOOOOO' \
         'OIOIOOOOOOOOOOOOOOOOOIOOOIOOOOOOOIOOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOIOOOI' \
         'OIOOOOOOOOOIOOOOOIOIOOOOOIOOOIOOOOOOOOOOOOOOOOOIOOOOOOOIOOOOOOOOOOOIOOOOOOOOOOOOOOOOOIOOOOOOOOOOOOOOOIOO' \
         'OOOIOIOOOOOOOOOOOIOOOOOIOOOOOOOOOIOIOOOOOOOOOIOIOOOOOIOOOOOOOOOIOOOOOOOOOOOOOIOOOIOOOOOOOOOOOOOOOOOOOOOO' \
         'OIOIOOOOOOOOOOOOOOOIOIOOOOOOOOOIOIOOOOOOOOOIOOOOOOOOOOOOOOOOOOOIOOOIOIOOOIOOOOOOOIOOOOOOOOOOOOOOOIOOOOOI' \
         'OOOOOIOIOOOOOOOOOOOIOOOOOOOOOOOOOOOIOOOOOOOIOOOIOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOIOOOOOOOOOIOIOOOOOI' \
         'OOOIOOOOOIOOOOOIOOOOOOOIOOOOOIOOOIOOOOOOOOOOOIOOOOOIOOOOOOOIOOOOOOOOOOOIOOOIOOOOOOOOOOOOOIOOOOOOOOOOOIOO' \
         'OOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOIOOOOOIOIOOOOOOOOOOOOOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOO' \
         'OIOOOOOOOOOIOOOOOIOOOOOOOOOOOOOIOOOIOIOOOOOIOOOOOOOOOIOOOOOOOIOOOOOIOOOIOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOO' \
         'OOOIOOOOOOOOOOOOOIOOOOOOOOOIOIOOOOOOOOOOOIOOOOOOOOOIOIOOOOOOOOOOOOOOOIOIOOOOOOOOOOOOOOOOOIOOOOOOOOOOOOOO' \
         'OOOOOOOOOIOOOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOOOIOOOOOOOOOOOOOOOOOIOOOOOIOIOOOOOOOOOOOOOOOOOIOOOIOOOOOI' \
         'OIOOOOOOOOOIOOOOOOOIOOOOOOOOOIOOOOOIOOOOOIOOOOOOOIOOOIOOOOOIOIOOOOOOOOOIOIOOOOOOOOOOOIOOOIOOOOOIOOOOOIOI' \
         'OOOOOOOOOOOIOOOIOOOOOOOOOOOOOIOOOOOOOOOOOOOOOOOIOOOIOOOOOIOOOOOOOOOOOOOOOOOOOIOOOIOOOOOOOIOOOOOIOOOIOOOO' \
         'OOOIOOOIOOOOOOOOOOOOOIOOOOOIOOOIOOOOOOOOOOOOOIOOOOOOOOOOOIOOOIOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOIOOOOOO' \
         'OOOOOOOOOOOOOOOOOIOOOOOIOOOOOIOOOOOOOOOOOIOOOOOOOOOOOIOOOOOOOOOOOOOIOOOOOIOOOIOIOOOIOOOOOOOOOOOOOOOOOIOO' \
         'OOOIOOOOOOOOOOOIOOOOOOOIOOOOOIOOOIOOOOOOOOOOOIOIOOOOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOOOOOO' \
         'OIOIOOOOOIOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOOOOOIOOOOOIOOOOOOOOOIOOOOOOOOOOOIOOOOOIOIOOOIOOOOOOOIOOOOOOOOOI' \
         'OOOOOIOOOOOIOOOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOOOOOIOOOOOIOOOIOOOOOOOIOOOOOOOOOOOIOOOOOOOOOOOOOOOOOIOOOOOO' \
         'OOOIOIOOOOOOOOOIOIOOOIOOOOOIOOOOOOOOOOOOOOOOOOOIOOOOOIOOOIOOOOOOOOOOOOOIOOOIOIOOOIOOOOOOOOOOOOOIOOOOOIOO' \
         'OOOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOIOOOOOIOOOOOOOIOOOOOOOOOIOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOI' \
         'OOOOOIOIOOOOOOOOOOOIOOOIOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOOOIOOOOOOOIOOOOOI' \
         'OOOOOOOOOIOIOOOIOOOOOOOOOOOOOOOOOOOIOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOIOIOOOOOOOOOIOOOOOOOOOOOOOIOOOIOIOO' \
         'OOOOOOOOOIOOOOOIOOOOOOOOOOOOOOOIOOOOOIOOOOOOOIOOOIOOOOOOOIOOOIOOOOOIOOOOOOOIOOOOOIOOOOOIOOOOOOOOOOOIOOOO' \
         'OIOOOIOOOOOIOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOIOOOIOOOOOOOOOOOOOOOOOOOIOOOIOOOOOOOOOOOIOIOOOOOOOOOIOOOOOIOI' \
         'OOOOOOOOOIOOOOOOOOOOOIOIOOOIOOOOOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOOOOOOOOOOOOOOOOOIOOOOOIOOOIOOOOOOOIOO' \
         'OOOOOOOIOOOOOOOOOOOIOOOOOIOIOOOOOOOOOOOOOOOOOOOOOOOOOOOIOIOOOOOIOOOIOIOOOOOOOOOOOOOOOIOOOOOOOOOOOIOIOOOO' \
         'OIOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOOOOOOOIOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOOOOOIOOOOOIOOOIOOOOOOOOOOOOOI' \
         'OOOOOIOOOIOOOOOOOOOOOIOOOOOOOIOOOOOIOOOOOOOOOOOIOOOIOOOOOIOOOOOOOOOOOIOOOOOIOOOOOOOOOOOIOIOOOOOOOOOOOOOO' \
         'OIOOOOOOOOOOOOOOOOOOOIOOOIOIOOOOOOOOOIOOOOOOOOOOOOOOOOOIOOOOOOOIOOOIOOOOOOOOOOOOOIOOOIOIOOOOOIOOOOOOOOOO' \
         'OOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOIOOOOOIOOOOOIOOOOOOOOOIOOOOOIOIOOOOOOOOOIOIOOOIOIOOOOOOOOOOOOOOOOOOOOOIOI' \
         'OOOIOOOOOIOOOOOIOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOIOOOOOOOOOIOOOOOOOOOOOIOOOOOIOOOOOOOIOOOIOOOOOOOOOOOOOOOO' \
         'OOOOOOOOOOOOOOOOOOOIOOOOOOOOOOOOOIOOOOOOOOOOOIOOOOOIOOOIOOOOOIOIOOOOOOOOOOOIOOOOOIOOOOOOOOOOOIOOOOOOOOOO' \
         'OOOOOIOIOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOOOOOIOIOOOOOOOOOOOIOOOOOIOOOIOOOOOIOOOOOOOOOOOOOOOOOIOIOOOOOO' \
         'OOOOOIOOOOOIOOOIOOOOOOOOOOOIOOOOOOOIOOOOOIOOOOOOOOOOOIOOOIOOOOOIOOOOOOOOOOOIOOOOOIOIOOOOOOOOOOOIOOOOOOOO' \
         'OOOIOOOIOOOOOOOOOOOOOIOOOOOIOOOOOOOOOOOOOOOIOOOOOIOIOOOOOOOOOIOOOOOOOIOOOOOOOOOOOOOOOOOIOOOOOIOOOOOOOOOO' \
         'OOOOOOOOOOOOOOOO'

def checkio(number):
    return primes[number] == 'I'

print(checkio(2))